apiVersion: v2
name: apicurio-registry
description: Install and configure Apicurio Registry in Kubernetes.
type: application
version: 0.0.0 # actual version is managed by git tag
appVersion: 0.0.0 # actual version is managed by git tag

home: https://github.com/eshepelyuk/apicurio-registry-helm

sources:
  - https://github.com/apicurio/apicurio-registry
  - https://github.com/Apicurio/apicurio-registry-content-sync-operator

maintainers:
  - name: Ievgenii Shepeliuk
    email: eshepelyuk@gmail.com
    url: https://github.com/eshepelyuk

keywords:
  - schema-registry
  - kafka
  - kubernetes
  - ui
  - streaming
  - openapi
  - asyncapi
  - swagger
