registry:
  enabled: true

  ## uncomment and adjust for kafka persistence
  # kafka:
  #   bootstrapServers: kafka1:9092,kafka2:9092

  ## uncomment and adjust for sql persistence
  # sql:
  #   url: jdbc:postgresql://postgres/apicurio-registry
  #   username: apicurio
  #   password: apicurio-password

  image:
    registry: "quay.io"
    repository: "apicurio/apicurio-registry"
    tag: "2.0.0.Final"
  resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 1300Mi
    # requests:
    #   cpu: 200m
    #   memory: 600Mi

sync:
  enabled: true
  image:
    registry: "quay.io"
    repository: "apicurio/apicurio-registry-kube-sync"
    tag: "latest-snapshot"
  # registryUrl:
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 800Mi
    # requests:
    #   cpu: 200m
    #   memory: 600Mi

