# imagePullSecrets:
# securityContext:
# affinity:
# tolerations:

registry:
  enabled: true

  ## uncomment and adjust for kafka persistence
  # kafka:
  #   bootstrapServers: kafka1:9092,kafka2:9092

  ## uncomment and adjust for sql persistence
  # sql:
  #   url: jdbc:postgresql://postgres/apicurio-registry
  #   username: apicurio
  #   password: apicurio-password

  image:
    registry: "quay.io"
    repository: "apicurio/apicurio-registry"
    tag: "2.3.1.Final"
  # optional node selector
  nodeSelector: {}
  # optional init containers
  initContainers: {}
  # optional liveliness probe
  livenessProbe:
    enabled: false
    #prefix: ""
    #path: "/health/ready"
    #port: 8787
    #httpGetExtra: {}
    #initialDelaySeconds: 0
    #periodSeconds: 30
    #timeoutSeconds: 5
    #successThreshold: 1
    #failureThreshold: 3
  # optional readiness probe
  readinessProbe:
    enabled: false
    #prefix: ""
    #path: "/health/ready"
    #port: 8787
    #httpGetExtra: {}
    #initialDelaySeconds: 0
    #periodSeconds: 30
    #timeoutSeconds: 5
    #successThreshold: 1
    #failureThreshold: 3
  # list of extra volume mounts
  extraVolumeMounts: []
    # - name: kafkauser
    #   mountPath: /opt/user
    #   readOnly: true
  # list of extra volumes
  extraVolumes: []
    # - name: kafkauser
    #   secret:
    #     secretName: kafka-user
  # list of name, value pairs of extra environment vars
  extraEnv: []
    # - name: SOME_ENV
    #   value: SOME_VALUE
  resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 1300Mi
    # requests:
    #   cpu: 200m
    #   memory: 600Mi

  ingress:
    enabled: false
    host: "apicurio.local"
    path: "/"
    tls: false
    annotations: {}
    labels: {}

sync:
  enabled: true
  image:
    registry: "quay.io"
    repository: "apicurio/apicurio-registry-kube-sync"
    tag: "d0e2505"
  # optional node selector
  nodeSelector: {}
  # optional init containers
  initContainers: {}
  # optional liveliness probe
  livenessProbe:
    enabled: false
    #prefix: ""
    #path: "/health/ready"
    #port: 8787
    #httpGetExtra: {}
    #initialDelaySeconds: 0
    #periodSeconds: 30
    #timeoutSeconds: 5
    #successThreshold: 1
    #failureThreshold: 3
  # optional readiness probe
  readinessProbe:
    enabled: false
    #prefix: ""
    #path: "/health/ready"
    #port: 8787
    #httpGetExtra: {}
    #initialDelaySeconds: 0
    #periodSeconds: 30
    #timeoutSeconds: 5
    #successThreshold: 1
    #failureThreshold: 3
  # list of extra volume mounts
  extraVolumeMounts: []
    # - name: kafkauser
    #   mountPath: /opt/user
    #   readOnly: true
  # list of extra volumes
  extraVolumes: []
    # - name: kafkauser
    #   secret:
    #     secretName: kafka-user
  # registryUrl:
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 800Mi
    # requests:
    #   cpu: 200m
    #   memory: 600Mi

