{{- if .Values.sync.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apicurio-registry.name" . }}-sync
  labels:
    {{- include "apicurio-registry.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "apicurio-registry.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: sync
  template:
    metadata:
      labels:
        {{- include "apicurio-registry.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: sync
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.securityContext }}
      securityContext:
        {{ toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "apicurio-registry.name" . }}
      {{- if .Values.sync.initContainers }}
      initContainers:
        {{- range $key, $value := .Values.sync.initContainers }}
        - name: {{ $key }}
{{ toYaml $value | indent 10 }}
        {{- end }}
      {{- end }}
      containers:
        - name: sync
          image: {{ .Values.sync.image.registry }}/{{ .Values.sync.image.repository }}:{{ .Values.sync.image.tag }}
          {{- with .Values.sync.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          imagePullPolicy: "Always"
          env:
            - name: APICURIO_REGISTRY_URL
              value: {{ coalesce .Values.sync.registryUrl (printf "http://%s:8080/apis/registry/v2" (include "apicurio-registry.name" .)) }}
            - name: QUARKUS_LOG_LEVEL
              value: INFO
            - name: LOG_LEVEL
              value: DEBUG
            - name: WATCH_NAMESPACES
              value: {{ .Release.Namespace }}
          ports:
            - containerPort: 8787
              name: http
              protocol: TCP
          {{- if .Values.sync.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.sync.livenessProbe.prefix | default "" }}{{ .Values.sync.livenessProbe.path }}
              port: {{ .Values.sync.livenessProbe.port }}
            {{- if .Values.sync.livenessProbe.httpGetExtra }}
              {{- toYaml .Values.sync.livenessProbe.httpGetExtra | trim | nindent 14 }}
            {{- end }}
            initialDelaySeconds: {{ .Values.sync.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.sync.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.sync.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.sync.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.sync.livenessProbe.failureThreshold }}
          {{- else }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8787
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          {{- end }}
          {{- if .Values.sync.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.sync.readinessProbe.prefix | default "" }}{{ .Values.sync.readinessProbe.path }}
              port: {{ .Values.sync.readinessProbe.port }}
              {{- if .Values.sync.readinessProbe.httpGetExtra }}{{ toYaml .Values.sync.readinessProbe.httpGetExtra | trim | nindent 14 }}{{ end }}
            initialDelaySeconds: {{ .Values.sync.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.sync.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.sync.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.sync.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.sync.readinessProbe.failureThreshold }}
          {{- else }}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8787
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          {{- end }}
          {{- with .Values.sync.resources }}
          resources:
            {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.sync.extraVolumeMounts  }}
          volumeMounts:
            {{- toYaml .Values.sync.extraVolumeMounts | nindent 12 }}
          {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.sync.extraVolumes  }}
      volumes:
        {{- toYaml .Values.sync.extraVolumes | nindent 8 }}
      {{- end }}
{{- end }}
