name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '*.puml'
      - '.github/workflows/release.yaml'
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20
      - uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .commitlintrc.yml
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: volesen/setup-skaffold@v1.1
        with:
          version: v1.38.0
      - uses: extractions/setup-just@v1
      - run: ./test/linter/test.sh
      - run: |
          helm plugin install https://github.com/quintush/helm-unittest
          helm unittest -f test/unit/*.yaml -3 .
      - uses: AbsaOSS/k3d-action@v1.5.0
        with:
          cluster-name: "k3d"
          use-default-registry: true
          args: >-
            --config ./test/e2e/k3d.yaml
      - run: |
          skaffold config set default-repo "registry.localhost:5000"
      - run: skaffold run
      - run: helm test apc-reg --logs
