name: Release
on:
  workflow_dispatch
jobs:
  rel_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: bahmutov/npm-install@v1.7.7
      - name: semantic-release
        run: npx semantic-release
        env:
          HELM_EXPERIMENTAL_OCI: 1
          REGISTRY_USERNAME: ${{ github.repository_owner }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
